export const partsOfSpeech = new Map([
    ["aj", "adjective"],
    ["ap", "apposition"],
    ["av", "general adverb"],
    ["cc", "conjunction"],
    ["cs", "subjunction"],
    ["dd", "demonstrative determiner"],
    ["dp", "possessive determiner"],
    ["dq", "quantifier"],
    ["ex", "exclamation"],
    ["fn", "foreign name"],
    ["fw", "foreign word"],
    ["im", "infinitive marker"],
    ["nc.f", "feminine noun"],
    ["nc.m", "masculine noun"],
    ["nc.n", "neuter noun"],
    ["np.f", "feminine name"],
    ["np.m", "masculine name"],
    ["np.n", "neuter name"],
    ["pe", "personal pronoun"],
    ["pi", "indefinite pronoun"],
    ["pq", "interrogative pronoun"],
    ["vb.a", "active verb"],
    ["vb.r", "reflexive verb"]
]);